site_name: My Blogs
site_url: https://wangzhengquan.github.io/blog
theme: material
plugins:
  - search
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
nav: 
  - 简介: 'index.md'
  - Algorithms:
    - Using a Stack to Evaluate an Expression: 'Algorithms/Using_a_Stack_to_Evaluate_an_Expression.md'
    - Using two stacks to Evaluate an Expression: 'Algorithms/Using two stacks to Evaluate an Expression.md'
  - Shell:
    - Shell Command: 'Shell/Shell Command.md'
    - Shell Script: 'Shell/Shell Script.md'
  - MacOS:
    - Launching Custom Daemons Using launchd: 'MacOS/Launching Custom Daemons Using launchd.md'
    - MacOS常用命令: 'MacOS/MacOS常用命令.md'
    - MacOS必备: 'MacOS/MacOS必备.md'
  - Unbuntu:
    - Fix “No Wi-Fi Adapter Found” Error on Ubuntu: 'Unbuntu/fix-the-no-wi-fi-adapter-found-error-on-ubuntu.md'
  - Vim:
    - Vim常用命令: 'Vim/vim常用命令.md'
  - 编辑器:
    - Sublime: 'editor/Sublime.md'
    - VSCode: 'editor/VSCode.md'
  - GCC:
    - GCC compiling processes: 'GCC/GCC compiling processes.md'
    - GCC Linking: 'GCC/GCC Linking.md'
    - Tools for Manipulating Object Files: 'GCC/Tools for Manipulating Object Files.md'
  - GDB:
    - gdb demo: 'GDB/gdb demo.md'
    - Summary of GDB commands: 'GDB/gdbnotes-x86-64.pdf'
    - GDB Cheat Sheet: 'GDB/GDB Cheat Sheet.pdf'
  - 编程语言:
    - Assembly:
      - Inline assembly for x86: 'ProgramingLanguage/assembly/Inline assembly for x86.md'
    - C:
      - C语言要点: 'ProgramingLanguage/C/C_takeaway.md'
    - C++:
      - operator overload: 'ProgramingLanguage/C++/operator overload.md'
      - friend: 'ProgramingLanguage/C++/friend.md'
  - 收藏:
    - AI Tools: "save/ai_tools.md"
    - 网络大学: "save/online_university.md"
    - 网址收藏: "save/web_site.md"
  - Markdown:
    - Markdown Syntax: "Markdown/Markdown Syntax.md"
    - Markdown模版: "Markdown/Markdown模版.md"
  - Git:
    - Git commands: "Git/Git commands.md"
  - SSH:
    - SSH command: 'SSH/SSH command.md'
    - SSH install: 'SSH/SSH install.md'
    - SSH login without password: 'SSH/SSH login without password.md'
  - Vagrant:
    - Vagrant tutorial: 'Vagrant/Vagrant tutorial.md'
  - docker:
    - docker: 'docker/docker.md'
   
